// Generated by CoffeeScript 1.4.0
var SortableHandler, fetchSpine;

fetchSpine = function() {
  return $.ajax({
    type: "GET",
    url: "" + BASE_URL + "my/books/" + BOOK_ID + "/spine.json",
    dataType: "json",
    success: function(r) {
      var compiled;
      console.log(r);
      compiled = _.template("<tr>\n  <td><%= BookSpine.id %></td>\n  <td><%= Article.id %></td>\n  <td><%= Article.subject %></td>\n  <td><%= Article.created %></td>\n  <td><%= BookSpine.order %></td>\n  <td><a href='' class='btn-mini'>delete</a></td>\n</tr>");
      return $.each(r, function(index, value) {
        var html;
        html = compiled(value);
        return $("#sort3").find("tbody").html(html);
      });
    }
  });
};

SortableHandler = (function() {

  SortableHandler.prototype.initialized = false;

  function SortableHandler(el, helper) {
    this.el = el;
    this.helper = helper;
    console.log(this.el);
  }

  SortableHandler.prototype.fixHelper = function(e, ui) {
    ui.children().each(function() {
      return $(this).width($(this).width());
    });
    return ui;
  };

  SortableHandler.prototype.disable = function() {
    console.log('disable');
    $(this.el).sortable("disable");
    return this.hideButtons();
  };

  SortableHandler.prototype.enable = function() {
    console.log('enable');
    if (!this.initialized) {
      console.log(1);
      $(this.el).sortable({
        helper: this.fixHelper
      }).disableSelection();
      this.initialized = true;
    } else {
      console.log(2);
      $(this.el).sortable("enable");
    }
    return this.showButtons();
  };

  SortableHandler.prototype.showButtons = function() {
    return $('.ctl-btn').show();
  };

  SortableHandler.prototype.hideButtons = function() {
    return $('.ctl-btn').hide();
  };

  return SortableHandler;

})();

$(document).ready(function() {
  var handler;
  fetchSpine();
  handler = new SortableHandler('#sort3 tbody');
  $('#btn-enable-sortable').click(function() {
    return handler.enable();
  });
  $('#btn-apply-sort').click(function() {
    return handler.disable();
  });
  $('#btn-cancel-sort').click(function() {
    return handler.disable();
  });
  return $("#btn1").click(function() {
    $("#myModal").modal({
      keyboard: false
    });
    return $.ajax({
      type: "GET",
      url: BASE_URL + "my/articles.json",
      dataType: "json",
      success: function(r) {
        var compiled;
        console.log(r);
        compiled = _.template("<tr>\n  <td><input type='checkbox' /></td>\n  <td><%= id %></td>\n  <td><%= category_id %></td>\n  <td><%= subject %></td>\n  <td><%= created %></td>\n</tr>\"");
        return $.each(r, function(index, value) {
          var html;
          html = compiled(value);
          return $("#article_list tbody").append(html);
        });
      }
    });
  });
});
